name: Deploy Backend Application

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Backend to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Backend Code
      uses: actions/checkout@v3

    - name: Clone Backend Repository on EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key.pem
        chmod 400 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@52.66.145.37 << 'EOF'
          cd /home/ec2-user/test || git clone https://github.com/chaaviesol/rx-backend.git /home/ec2-user/test
          cd /home/ec2-user/test
          git pull
        EOF

    - name: Cleanup SSH Key
      run: rm private_key.pem
